// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0sTtm4IHDYRk61evjU7rDz8DTXDqjp4',
    appId: '1:328003399661:web:fc4cec734ef80b804781e4',
    messagingSenderId: '328003399661',
    projectId: 'bloc-novatech',
    authDomain: 'bloc-novatech.firebaseapp.com',
    storageBucket: 'bloc-novatech.appspot.com',
    measurementId: 'G-9LBTH88DZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYHJAtSyF3AQBf73DlaKDht3QvjL6pTo',
    appId: '1:328003399661:android:6e68a3b7e4203fdd4781e4',
    messagingSenderId: '328003399661',
    projectId: 'bloc-novatech',
    storageBucket: 'bloc-novatech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7cmqXE3nEhNBXKNw5W9EQGFJA85yClHQ',
    appId: '1:328003399661:ios:17bbcd5fe7c373f94781e4',
    messagingSenderId: '328003399661',
    projectId: 'bloc-novatech',
    storageBucket: 'bloc-novatech.appspot.com',
    androidClientId: '328003399661-3akfgi2ero4sfqihq7h8571nf2a0m8l8.apps.googleusercontent.com',
    iosClientId: '328003399661-82of5hp7sf8qd8r478csnq53k8sr5oup.apps.googleusercontent.com',
    iosBundleId: 'com.novatech.bloc',
  );
}
